spring:
  application:
    name: web
  config:
    import:
      - classpath:mysql.yaml
      - classpath:vault.yaml
      - classpath:seaweedfs.yaml
      - classpath:facebook.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
