server.port=8084

services.facebook.url=${FACEBOOK_SERVICE_URL:http://localhost:8081}
services.secret-manager.url=${SECRET_MANAGER_SERVICE_URL:http://localhost:8082}
services.storage.url=${STORAGE_SERVICE_URL:http://localhost:8083}
